services:
  server:
    build:
      context: .
      target: final
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      CorsOrigin: http://localhost:4200
    ports:
      - "8080:8080"
    restart: unless-stopped
